### ISSUE TITLE
It is not working - application entry file is not found

### ISSUE THREAD

**Issue by rostandkenne** [avatsaev/nativescript-master-detail-angular2#1]
Hi,

I have followed the README steps but it is not working (ios and andoid). An entrypoint is missing.

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: com.tns.NativeScriptException:

**Comment by avatsaev** [comment]
I'm working on a fix right now.

Will close when updated.

Thanks.

**Comment by born2net** [comment]
yes same issue here
please let us know when fixed...
really liking what I saw in source code so far

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by avatsaev** [comment]
There is been some major refactoring I would suggest deleting the previous project and creating a new one.

**Comment by born2net** [comment]
will do tx
